[package]
name = "owner_of_session"
version = "1.1.1"
edition = "2018"

[dependencies]
casper-contract = "1.4.3"
casper-types = "1.4.5"

[[bin]]
name = "owner_of_call"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true