name: ci-casper-rust-contract

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

  pull_request:
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: Swatinem/rust-cache@v2

      - name: Get nightly toolchain from file
        id: nightly-toolchain
        run: echo "::set-output name=version::$(cat resources/rust-toolchain.in)"

      - run: sudo apt update && sudo apt install -y build-essential wabt
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.nightly-toolchain.outputs.version }}
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - run: make prepare

      - name: "Check linting"
        run: make check-lint

      - name: "Tests"
        run: make test

      - name: "Build"
        run: make build-contract
